version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      REDIS_HOST: redis

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wallet_service
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    restart: always
    command: --init-file /docker-entrypoint-initdb.d/init.sql


  redis:
    image: "redis:alpine"

volumes:
  db_data: {}